### ISSUE TITLE
Build error: import not found or unreadable: ../../node_modules/bulma...

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/documentation#122]
## Requirement - what kind of business use case are you trying to solve?

Contribute a change to the docs.

## Problem - what in Jaeger blocks you from solving the requirement?

Running into an error when attempting to build the docs.

**Note**: I'm running hugo version 0.46.

When I run `make develop` I get the following error:

```bash
make develop
hugo server \
        --buildDrafts \
        --buildFuture \
        --disableFastRender \
        --ignoreCache
Building sites … ERROR 2018/08/07 21:24:15 error: failed to transform resource: SCSS processing failed: file "/Users/edwardfarro/dev/jaeger-docs/themes/jaeger-docs/assets/sass/variables.sass", line 15, col 1: File to import not found or unreadable: ../../node_modules/bulma/sass/utilities/initial-variables.
Total in 36 ms
Error: Error building site: logged 1 error(s)
make: *** [develop] Error 255
```

Looks like the sass is referring to files that were available before switching to the hugo asset pipeline, see line 2 and 10, below.

https://github.com/jaegertracing/documentation/blob/20f1b9daa63284d8d3d71919eaf151e932b18026/themes/jaeger-docs/assets/sass/style.sass#L1-L10

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Include the assets as a vendored resource.

## Any open questions to address

N/A

**Comment by tiffon** [comment]
@lucperkins I just wanted to touch base about this. Looks like there are assets in `node_modules/...` being referenced in `style.sass` but there isn't a `package.json` in the repo.

Are you able to do a fresh checkout and build?

**Comment by lucperkins** [comment]
Hmmm. This is odd because the site is building fine in Netlify but upon investigation it shouldn't be! Perhaps the `node_modules` is cached? I'll fix this.

**Comment by tiffon** [comment]
@lucperkins Awesome, thank you! Closing as this is fixed by #139.

**Comment by pavolloffay** [comment]
@lucperkins I still get the same issue:

```
make develop                                                                                                                                                                  10:35 
HUGO_PREVIEW=true \
hugo server \
        --buildDrafts \
        --buildFuture \
        --disableFastRender
Building sites … ERROR 2019/01/22 10:35:49 error: failed to transform resource: SCSS processing failed: file "/home/ploffay/projects/jaegertracing/documentation/themes/jaeger-docs/assets/sass/toc.sass", line 2, col 1: File to import not found or unreadable: vendor/tocbot. 
Total in 164 ms
Error: Error building site: logged 1 error(s)
make: *** [Makefile:6: develop] Error 255
```

Any tips how to solve it?

**Comment by yurishkuro** [comment]
I have the version listed in netlify.toml
```
$ hugo version
Hugo Static Site Generator v0.53/extended darwin/amd64 BuildDate: unknown
```

and `make develop` works fine. Since this is an old ticket, I assume it's no longer an issue.
